//Happy
//Romantic
//Alien Invasion


{"Title":"Avatar",
"Year":"2009",
"Rated":"PG-13",
"Released":"18 Dec 2009",
"Runtime":"162 min",
"Genre":"Action, Adventure, Fantasy",
"Director":"James Cameron","Writer":"James Cameron",
"Actors":"Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
"Plot":"A Paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home..",
"Language":"English, Spanish","Country":"USA, UK",
"Awards":"Won 3 Oscars. Another 73 wins & 100 nominations.",
"Poster":"http://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
"Metascore":"83",
"imdbRating":"7.9",
"imdbVotes":"743,277",
"imdbID":"tt0499549",
"Type":"movie",
"Response":"True"
}


{"Title":"Independence Day",
"Year":"1996",
"Rated":"PG-13",
"Released":"03 Jul 1996",
"Runtime":"145 min","Genre":"Action, Adventure, Sci-Fi",
"Director":"Roland Emmerich",
"Writer":"Dean Devlin, Roland Emmerich",
"Actors":"Will Smith, Bill Pullman, Jeff Goldblum, Mary McDonnell",
"Plot":"The aliens are coming and their goal is to invade and destroy. Fighting superior technology, Man's best weapon is the will to survive.",
"Language":"English",
"Country":"USA",
"Awards":"Won 1 Oscar. Another 28 wins & 31 nominations.",
"Poster":"http://ia.media-imdb.com/images/M/MV5BMTMwODY3NzQzNF5BMl5BanBnXkFtZTcwNzUxNjc0MQ@@._V1_SX300.jpg","Metascore":"59",
"imdbRating":"6.9",
"imdbVotes":"364,103",
"imdbID":"tt0116629",
"Type":"movie",
"Response":"True"
}

{"Title":"Titanic",
"Year":"1997",
"Rated":"PG-13",
"Released":"19 Dec 1997",
"Runtime":"194 min",
"Genre":"Drama, Romance",
"Director":"James Cameron",
"Writer":"James Cameron",
"Actors":"Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates",
"Plot":"A seventeen-year-old aristocrat, expecting to be married to a rich claimant by her mother, falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
"Language":"English, French, German, Swedish, Italian, Russian",
"Country":"USA",
"Awards":"Won 11 Oscars. Another 106 wins & 59 nominations.",
"Poster":"http://ia.media-imdb.com/images/M/MV5BMjExNzM0NDM0N15BMl5BanBnXkFtZTcwMzkxOTUwNw@@._V1_SX300.jpg",
"Metascore":"74",
"imdbRating":"7.7",
"imdbVotes":"637,458",
"imdbID":"tt0120338",
"Type":"movie",
"Response":"True"
}

//Dysfunctional Family Finds Functionality

{"Title":"The Family Stone",
"Year":"2005",
"Rated":"PG-13",
"Released":"16 Dec 2005",
"Runtime":"103 min",
"Genre":"Comedy, Drama, Romance",
"Director":"Thomas Bezucha",
"Writer":"Thomas Bezucha",
"Actors":"Claire Danes, Diane Keaton, Rachel McAdams, Dermot Mulroney",
"Plot":"An uptight, conservative, businesswoman accompanies her boyfriend to his eccentric and outgoing family's annual Christmas celebration and finds that she's a fish out of water in their free-spirited way of life.",
"Language":"English, American Sign Language",
"Cou
ntry":"USA",
"Awards":"Nominated for 1 Golden Globe. Another 4 wins & 6 nominations.",
"Poster":"http://ia.media-imdb.com/images/M/MV5BNTkwMjM4MjMxMV5BMl5BanBnXkFtZTcwNjM1OTQzMQ@@._V1_SX300.jpg",
"Metascore":"56",
"imdbRating":"6.3",
"imdbVotes":"44,243",
"imdbID":"tt0356680",
"Type":"movie",
"Response":"True"}

{
  "Title": "Garden State",
  "Year": "2004",
  "Rated": "R",
  "Released": "20 Aug 2004",
  "Runtime": "102 min",
  "Genre": "Comedy, Drama, Romance",
  "Director": "Zach Braff",
  "Writer": "Zach Braff",
  "Actors": "Zach Braff, Kenneth Graymez, George C. Wolfe, Austin Lysy",
  "Plot": "A quietly troubled young man returns home for his mother's funeral after being estranged from his family for a decade.",
  "Language": "English, Klingon",
  "Country": "USA",
  "Awards": "12 wins & 28 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMjc5MDE0NjkxOF5BMl5BanBnXkFtZTcwNzA0NTkyMw@@._V1_SX300.jpg",
  "Metascore": "67",
  "imdbRating": "7.6",
  "imdbVotes": "174,998",
  "imdbID": "tt0333766",
  "Type": "movie",
  "Response": "True"
}

{
  "Title": "8 Mile",
  "Year": "2002",
  "Rated": "R",
  "Released": "08 Nov 2002",
  "Runtime": "110 min",
  "Genre": "Drama, Music",
  "Director": "Curtis Hanson",
  "Writer": "Scott Silver",
  "Actors": "Eminem, Kim Basinger, Mekhi Phifer, Brittany Murphy",
  "Plot": "A young rapper, struggling with every aspect of his life, wants to make the most of what could be his final opportunity but his problems around gives him doubts.",
  "Language": "English",
  "Country": "USA, Germany",
  "Awards": "Won 1 Oscar. Another 10 wins & 19 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTU2MTgyOTk3MF5BMl5BanBnXkFtZTYwOTg2NTI5._V1_SX300.jpg",
  "Metascore": "77",
  "imdbRating": "6.9",
  "imdbVotes": "153,376",
  "imdbID": "tt0298203",
  "Type": "movie",
  "Response": "True"
}

//Silly
//Must find misplaced belongings

{
  "Title": "Dude, Where's My Car?",
  "Year": "2000",
  "Rated": "PG-13",
  "Released": "15 Dec 2000",
  "Runtime": "83 min",
  "Genre": "Comedy, Mystery, Sci-Fi",
  "Director": "Danny Leiner",
  "Writer": "Philip Stark",
  "Actors": "Ashton Kutcher, Seann William Scott, Jennifer Garner, Marla Sokoloff",
  "Plot": "Two potheads wake up after a night of partying and cannot remember where they parked their car.",
  "Language": "English, Japanese, French",
  "Country": "USA",
  "Awards": "5 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTg4ODcxOTgyOV5BMl5BanBnXkFtZTcwODI0NTI1MQ@@._V1_SX300.jpg",
  "Metascore": "30",
  "imdbRating": "5.5",
  "imdbVotes": "103,460",
  "imdbID": "tt0242423",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Harold & Kumar Go to White Castle",
  "Year": "2004",
  "Rated": "R",
  "Released": "30 Jul 2004",
  "Runtime": "88 min",
  "Genre": "Adventure, Comedy",
  "Director": "Danny Leiner",
  "Writer": "Jon Hurwitz, Hayden Schlossberg",
  "Actors": "John Cho, Ethan Embry, Rob Tinkler, Fred Willard",
  "Plot": "An Asian-American office worker and his Indian stoner friend embark on a quest to satisfy their desire for White Castle burgers.",
  "Language": "English, Hindi",
  "Country": "USA, Canada, Germany",
  "Awards": "3 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BNDQyMTg3Mzk4MV5BMl5BanBnXkFtZTcwMDM4NzUyMQ@@._V1_SX300.jpg",
  "Metascore": "64",
  "imdbRating": "7.2",
  "imdbVotes": "139,679",
  "imdbID": "tt0366551",
  "Type": "movie",
  "Response": "True"
}
{
  "Title": "Next Friday",
  "Year": "2000",
  "Rated": "R",
  "Released": "12 Jan 2000",
  "Runtime": "98 min",
  "Genre": "Comedy",
  "Director": "Steve Carr",
  "Writer": "Ice Cube (characters), DJ Pooh (characters), Ice Cube",
  "Actors": "Ice Cube, Mike Epps, Justin Pierce, John Witherspoon",
  "Plot": "Uncle Elroy and Day Day owe money on taxes so Craig finds a way to steal from the next door neighbors to pay off the taxes so Uncle Elroy's house doesn't get put up for auction.",
  "Language": "English",
  "Country": "USA",
  "Awards": "1 nomination.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTc2NzU0NTM0M15BMl5BanBnXkFtZTcwMDI0OTEyMQ@@._V1_SX300.jpg",
  "Metascore": "41",
  "imdbRating": "6.0",
  "imdbVotes": "21,880",
  "imdbID": "tt0195945",
  "Type": "movie",
  "Response": "True"
}

//Dog Escapes from his vage and wreaks havoc on outside world
{
  "Title": "Beethoven",
  "Year": "1992",
  "Rated": "PG",
  "Released": "03 Apr 1992",
  "Runtime": "87 min",
  "Genre": "Comedy, Drama, Family",
  "Director": "Brian Levant",
  "Writer": "John Hughes, Amy Holden Jones",
  "Actors": "Charles Grodin, Bonnie Hunt, Dean Jones, Nicholle Tom",
  "Plot": "A slobbering St. Bernard becomes the center of attention for a loving family, but its veterinarian secretly wants to kill him.",
  "Language": "English",
  "Country": "USA",
  "Awards": "1 win & 4 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTIxOTUxMTY5M15BMl5BanBnXkFtZTcwNzI2NDAyMQ@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "5.5",
  "imdbVotes": "40,656",
  "imdbID": "tt0103786",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Homeward Bound",
  "Year": "2009",
  "Rated": "TV-14",
  "Released": "15 Jan 2009",
  "Runtime": "60 min",
  "Genre": "Comedy, Drama, Romance",
  "Director": "Mark Tinker",
  "Writer": "Shonda Rhimes (created by), Sal Calleros",
  "Actors": "Kate Walsh, Tim Daly, Audra McDonald, Paul Adelstein",
  "Plot": "Addison is attracted to Wyatt, the rival practice's brash doctor, while Violet secretly dates Pete and Sheldon at the same time, and Cooper gets closer to Charlotte in a family emergency.",
  "Language": "English",
  "Country": "USA",
  "Awards": "N/A",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTQ4MDY1NTkxMF5BMl5BanBnXkFtZTgwOTYwMzIzMjE@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "8.3",
  "imdbVotes": "125",
  "imdbID": "tt1343660",
  "Type": "episode",
  "Response": "True"
},
{
  "Title": "Lassie",
  "Year": "1994",
  "Rated": "PG",
  "Released": "22 Jul 1994",
  "Runtime": "94 min",
  "Genre": "Family, Adventure",
  "Director": "Daniel Petrie",
  "Writer": "Eric Knight (character of Lassie), Matthew Jacobs, Gary Ross, Elizabeth Anderson",
  "Actors": "Tom Guiry, Helen Slater, Jon Tenney, Brittany Boyd",
  "Plot": "The dog everyone loves now leaps into the '90s in this all-new exciting, updated version of Lassie! Determined to start a new life in the country, the Turner Family - Dad, stepmom, little ...",
  "Language": "English",
  "Country": "USA",
  "Awards": "1 win & 1 nomination.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTYwNDg4NjMwMV5BMl5BanBnXkFtZTcwOTgzNTYxMQ@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "5.8",
  "imdbVotes": "3,251",
  "imdbID": "tt0110305",
  "Type": "movie",
  "Response": "True"
}
//Optimistic
//Everything in your life will work out great if you just believe

{
  "Title": "Angels in the Outfield",
  "Year": "1994",
  "Rated": "PG",
  "Released": "15 Jul 1994",
  "Runtime": "102 min",
  "Genre": "Comedy, Family, Fantasy",
  "Director": "William Dear",
  "Writer": "Dorothy Kingsley, George Wells, Richard Conlin, Dorothy Kingsley (screenplay), George Wells (screenplay), Holly Goldberg Sloan (screenplay)",
  "Actors": "Danny Glover, Brenda Fricker, Tony Danza, Christopher Lloyd",
  "Plot": "When a boy prays for a chance to have a family if the California Angels win the pennant, angels are assigned to make that possible.",
  "Language": "English",
  "Country": "USA",
  "Awards": "1 win & 4 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTIzOTQ5MDM0N15BMl5BanBnXkFtZTcwMDk3NjAwMQ@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "6.0",
  "imdbVotes": "18,896",
  "imdbID": "tt0109127",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Shawshank Redemption",
  "Year": "2013",
  "Rated": "N/A",
  "Released": "04 Jul 2013",
  "Runtime": "N/A",
  "Genre": "Short, Comedy",
  "Director": "Sunday Boling",
  "Writer": "Amanda Jaros",
  "Actors": "Amanda Jaros, Mackenzie Marsh, Bob Turton",
  "Plot": "N/A",
  "Language": "N/A",
  "Country": "N/A",
  "Awards": "N/A",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMjMwMzE3NzIyNV5BMl5BanBnXkFtZTcwNzMwMzk0OA@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "N/A",
  "imdbVotes": "N/A",
  "imdbID": "tt3125798",
  "Type": "episode",
  "Response": "True"
},
{
  "Title": "Little Miss Sunshine",
  "Year": "2006",
  "Rated": "R",
  "Released": "18 Aug 2006",
  "Runtime": "101 min",
  "Genre": "Adventure, Comedy, Drama",
  "Director": "Jonathan Dayton, Valerie Faris",
  "Writer": "Michael Arndt",
  "Actors": "Abigail Breslin, Greg Kinnear, Paul Dano, Alan Arkin",
  "Plot": "A family determined to get their young daughter into the finals of a beauty pageant take a cross-country trip in their VW bus.",
  "Language": "English",
  "Country": "USA",
  "Awards": "Won 2 Oscars. Another 70 wins & 67 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTgzNTgzODU0NV5BMl5BanBnXkFtZTcwMjEyMjMzMQ@@._V1_SX300.jpg",
  "Metascore": "80",
  "imdbRating": "7.9",
  "imdbVotes": "303,495",
  "imdbID": "tt0449059",
  "Type": "movie",
  "Response": "True"
}

//At least you don’t have cancer
{
  "Title": "Forrest Gump",
  "Year": "1994",
  "Rated": "PG-13",
  "Released": "06 Jul 1994",
  "Runtime": "142 min",
  "Genre": "Drama, Romance",
  "Director": "Robert Zemeckis",
  "Writer": "Winston Groom (novel), Eric Roth (screenplay)",
  "Actors": "Tom Hanks, Rebecca Williams, Sally Field, Michael Conner Humphreys",
  "Plot": "Forrest Gump, while not intelligent, has accidentally been present at many historic moments, but his true love, Jenny Curran, eludes him.",
  "Language": "English",
  "Country": "USA",
  "Awards": "Won 6 Oscars. Another 40 wins & 47 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTQwMTA5MzI1MF5BMl5BanBnXkFtZTcwMzY5Mzg3OA@@._V1_SX300.jpg",
  "Metascore": "82",
  "imdbRating": "8.8",
  "imdbVotes": "957,465",
  "imdbID": "tt0109830",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Finding Nemo",
  "Year": "2003",
  "Rated": "G",
  "Released": "30 May 2003",
  "Runtime": "100 min",
  "Genre": "Animation, Adventure, Comedy",
  "Director": "Andrew Stanton, Lee Unkrich",
  "Writer": "Andrew Stanton (original story by), Andrew Stanton (screenplay), Bob Peterson (screenplay), David Reynolds (screenplay)",
  "Actors": "Albert Brooks, Ellen DeGeneres, Alexander Gould, Willem Dafoe",
  "Plot": "After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.",
  "Language": "English",
  "Country": "USA",
  "Awards": "Won 1 Oscar. Another 44 wins & 49 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTY1MTg1NDAxOV5BMl5BanBnXkFtZTcwMjg1MDI5Nw@@._V1_SX300.jpg",
  "Metascore": "90",
  "imdbRating": "8.2",
  "imdbVotes": "530,572",
  "imdbID": "tt0266543",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Life Is Beautiful",
  "Year": "1997",
  "Rated": "PG-13",
  "Released": "12 Feb 1999",
  "Runtime": "116 min",
  "Genre": "Comedy, Drama, Romance",
  "Director": "Roberto Benigni",
  "Writer": "Vincenzo Cerami (story), Roberto Benigni (story)",
  "Actors": "Roberto Benigni, Nicoletta Braschi, Giorgio Cantarini, Giustino Durano",
  "Plot": "A Jewish man has a wonderful romance with the help of his humour, but must use that same quality to protect his son in a Nazi concentration camp.",
  "Language": "Italian, German, English",
  "Country": "Italy",
  "Awards": "Won 3 Oscars. Another 61 wins & 39 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTQwMTM2MjE4Ml5BMl5BanBnXkFtZTgwODQ2NTYxMTE@._V1_SX300.jpg",
  "Metascore": "59",
  "imdbRating": "8.6",
  "imdbVotes": "314,621",
  "imdbID": "tt0118799",
  "Type": "movie",
  "Response": "True"
},

{
  "Title": "Brian's Song",
  "Year": "1971",
  "Rated": "G",
  "Released": "30 Nov 1971",
  "Runtime": "73 min",
  "Genre": "Biography, Drama, Sport",
  "Director": "Buzz Kulik",
  "Writer": "William Blinn, Gale Sayers (book), Al Silverman (book)",
  "Actors": "James Caan, Billy Dee Williams, Jack Warden, Bernie Casey",
  "Plot": "Based on the real-life relationship between teammates Brian Piccolo and Gale Sayers and the bond established when Piccolo discovers that he is dying.",
  "Language": "English",
  "Country": "USA",
  "Awards": "Nominated for 1 Golden Globe. Another 9 wins & 7 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTkyNjQ3NTQ5Nl5BMl5BanBnXkFtZTcwMzk3NzUyMQ@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "7.6",
  "imdbVotes": "5,356",
  "imdbID": "tt0068315",
  "Type": "movie",
  "Response": "True"
}

//Campy
//Fake blood and bad makeup  - the 80s edition
{
  "Title": "Surf Nazis Must Die",
  "Year": "1987",
  "Rated": "R",
  "Released": "03 Jul 1987",
  "Runtime": "83 min",
  "Genre": "Action, Comedy, Drama",
  "Director": "Peter George",
  "Writer": "Jon Ayre (screenplay), Peter George (original story), Jon Ayre (original story)",
  "Actors": "Gail Neely, Robert Harden, Barry Brenner, Dawn Wildsmith",
  "Plot": "When the grandson of a gun wielding woman is murdered by neo-nazi surf punks in the post-apocalyptic future, this grandma hunts them down for some bloodthirsty revenge.",
  "Language": "English",
  "Country": "USA",
  "Awards": "N/A",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTUyOTEwNjAxMl5BMl5BanBnXkFtZTcwNDAwOTUxMQ@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "3.4",
  "imdbVotes": "3,778",
  "imdbID": "tt0094077",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Dead Alive",
  "Year": "1992",
  "Rated": "R",
  "Released": "12 Feb 1993",
  "Runtime": "104 min",
  "Genre": "Comedy, Horror",
  "Director": "Peter Jackson",
  "Writer": "Stephen Sinclair (story), Stephen Sinclair (screenplay), Fran Walsh (screenplay), Peter Jackson (screenplay)",
  "Actors": "Timothy Balme, Diana Peñalver, Elizabeth Moody, Ian Watkin",
  "Plot": "A young man's mother is bitten by a Sumatran rat-monkey. She gets sick and dies, at which time she comes back to life, killing and eating dogs, nurses, friends, and neighbors.",
  "Language": "English, Spanish",
  "Country": "New Zealand",
  "Awards": "13 wins & 5 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTcwMzY5MTYxNF5BMl5BanBnXkFtZTYwOTUwOTc4._V1_SX300.jpg",
  "Metascore": "54",
  "imdbRating": "7.6",
  "imdbVotes": "69,529",
  "imdbID": "tt0103873",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "The Evil Dead",
  "Year": "1981",
  "Rated": "NC-17",
  "Released": "24 Apr 1983",
  "Runtime": "85 min",
  "Genre": "Horror",
  "Director": "Sam Raimi",
  "Writer": "Sam Raimi",
  "Actors": "Bruce Campbell, Ellen Sandweiss, Richard DeManincor, Betsy Baker",
  "Plot": "Five friends travel to a cabin in the woods, where they unknowingly release flesh-possessing demons.",
  "Language": "English",
  "Country": "USA",
  "Awards": "3 wins & 1 nomination.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTkyNzI4MTE2OF5BMl5BanBnXkFtZTYwODE2NzM5._V1_SX300.jpg",
  "Metascore": "70",
  "imdbRating": "7.6",
  "imdbVotes": "118,223",
  "imdbID": "tt0083907",
  "Type": "movie",
  "Response": "True"
}

//You can never have too much purple

{
  "Title": "The Grand Budapest Hotel",
  "Year": "2014",
  "Rated": "R",
  "Released": "28 Mar 2014",
  "Runtime": "100 min",
  "Genre": "Adventure, Comedy, Drama",
  "Director": "Wes Anderson",
  "Writer": "Stefan Zweig (inspired by the writings of), Wes Anderson (screenplay), Wes Anderson (story), Hugo Guinness (story)",
  "Actors": "Ralph Fiennes, F. Murray Abraham, Mathieu Amalric, Adrien Brody",
  "Plot": "The adventures of Gustave H, a legendary concierge at a famous hotel from the fictional Republic of Zubrowka between the first and second World Wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.",
  "Language": "English, French",
  "Country": "USA, Germany, UK",
  "Awards": "Nominated for 4 Golden Globes. Another 43 wins & 83 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_SX300.jpg",
  "Metascore": "88",
  "imdbRating": "8.1",
  "imdbVotes": "232,366",
  "imdbID": "tt2278388",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Oh Brother, Where Art Thou?",
  "Year": "1991",
  "Rated": "TV-PG",
  "Released": "21 Feb 1991",
  "Runtime": "23 min",
  "Genre": "Animation, Comedy",
  "Director": "Wesley Archer",
  "Writer": "Matt Groening (created by), James L. Brooks (developed by), Matt Groening (developed by), Sam Simon (developed by), Jeff Martin",
  "Actors": "Dan Castellaneta, Julie Kavner, Nancy Cartwright, Yeardley Smith",
  "Plot": "After Grampa is hospitalized, he reveals that Homer has a half-brother, and the family soon discovers the brother, named Herb, owns a car company. However Herb's hiring of Homer to design a new car may be his undoing.",
  "Language": "English",
  "Country": "USA",
  "Awards": "N/A",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTg0MzcyNTM4Nl5BMl5BanBnXkFtZTgwNjc1NTQ2MjE@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "7.7",
  "imdbVotes": "1,162",
  "imdbID": "tt0701191",
  "Type": "episode",
  "Response": "True"
},
{
  "Title": "Sin City",
  "Year": "2005",
  "Rated": "R",
  "Released": "01 Apr 2005",
  "Runtime": "124 min",
  "Genre": "Crime, Thriller",
  "Director": "Frank Miller, Robert Rodriguez, Quentin Tarantino",
  "Writer": "Frank Miller (graphic novels)",
  "Actors": "Jessica Alba, Devon Aoki, Alexis Bledel, Powers Boothe",
  "Plot": "A film that explores the dark and miserable town, Basin City, and tells the story of three different people, all caught up in violent corruption.",
  "Language": "English",
  "Country": "USA",
  "Awards": "24 wins & 34 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTI2NjUyMDUyMV5BMl5BanBnXkFtZTcwMzU0OTkyMQ@@._V1_SX300.jpg",
  "Metascore": "74",
  "imdbRating": "8.1",
  "imdbVotes": "554,847",
  "imdbID": "tt0401792",
  "Type": "movie",
  "Response": "True"
}

// Lonely
// Drunk
// If you drink enough you’ll probably become a famous writer
{
  "Title": "Factotum",
  "Year": "2005",
  "Rated": "R",
  "Released": "29 Apr 2005",
  "Runtime": "94 min",
  "Genre": "Comedy, Drama, Romance",
  "Director": "Bent Hamer",
  "Writer": "Charles Bukowski (novel), Bent Hamer, Jim Stark",
  "Actors": "Matt Dillon, Lili Taylor, Didier Flamand, Fisher Stevens",
  "Plot": "This drama centers on Hank Chinaski, the fictional alter-ego of \"Factotum\" author Charles Bukowski, who wanders around Los Angeles, CA trying to live off jobs which don't interfere with his primary interest, which is writing. Along the way, he fends off the distractions offered by women, drinking and gambling.",
  "Language": "English",
  "Country": "Norway, USA, Germany, France, Italy",
  "Awards": "3 wins & 3 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTMzMDYzOTg2N15BMl5BanBnXkFtZTcwMzE3ODQzMQ@@._V1_SX300.jpg",
  "Metascore": "71",
  "imdbRating": "6.6",
  "imdbVotes": "11,147",
  "imdbID": "tt0417658",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Sideways",
  "Year": "2004",
  "Rated": "R",
  "Released": "21 Jan 2005",
  "Runtime": "126 min",
  "Genre": "Comedy, Drama, Romance",
  "Director": "Alexander Payne",
  "Writer": "Rex Pickett (novel), Alexander Payne (screenplay), Jim Taylor (screenplay)",
  "Actors": "Paul Giamatti, Thomas Haden Church, Virginia Madsen, Sandra Oh",
  "Plot": "Two men reaching middle age with not much to show but disappointment, embark on a week long road trip through California's wine country, just as one is about to take a trip down the aisle.",
  "Language": "English, Armenian",
  "Country": "USA, Hungary",
  "Awards": "Won 1 Oscar. Another 130 wins & 49 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTU0Mjg3MzkxOV5BMl5BanBnXkFtZTYwNDU1OTY3._V1_SX300.jpg",
  "Metascore": "94",
  "imdbRating": "7.6",
  "imdbVotes": "133,463",
  "imdbID": "tt0375063",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "The Big Lebowski",
  "Year": "1998",
  "Rated": "R",
  "Released": "06 Mar 1998",
  "Runtime": "117 min",
  "Genre": "Comedy, Crime",
  "Director": "Joel Coen, Ethan Coen",
  "Writer": "Ethan Coen, Joel Coen",
  "Actors": "Jeff Bridges, John Goodman, Julianne Moore, Steve Buscemi",
  "Plot": "\"The Dude\" Lebowski, mistaken for a millionaire Lebowski, seeks restitution for his ruined rug and enlists his bowling buddies to help get it.",
  "Language": "English, German, Hebrew, Spanish",
  "Country": "USA, UK",
  "Awards": "1 win & 10 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTQ0NjUzMDMyOF5BMl5BanBnXkFtZTgwODA1OTU0MDE@._V1_SX300.jpg",
  "Metascore": "69",
  "imdbRating": "8.2",
  "imdbVotes": "430,072",
  "imdbID": "tt0118715",
  "Type": "movie",
  "Response": "True"
}

// Maybe you’re lonely because you suck
{
  "Title": "Frances Ha",
  "Year": "2012",
  "Rated": "R",
  "Released": "20 Jun 2013",
  "Runtime": "86 min",
  "Genre": "Comedy, Drama",
  "Director": "Noah Baumbach",
  "Writer": "Noah Baumbach, Greta Gerwig",
  "Actors": "Greta Gerwig, Mickey Sumner, Michael Esper, Adam Driver",
  "Plot": "A story that follows a New York woman (who doesn't really have an apartment), apprentices for a dance company (though she's not really a dancer), and throws herself headlong into her dreams, even as their possibility dwindles.",
  "Language": "English",
  "Country": "USA",
  "Awards": "Nominated for 1 Golden Globe. Another 8 wins & 27 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BOTY0NDQ2NzQ2N15BMl5BanBnXkFtZTcwMTU0OTkwOQ@@._V1_SX300.jpg",
  "Metascore": "82",
  "imdbRating": "7.4",
  "imdbVotes": "31,194",
  "imdbID": "tt2347569",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Never Been Kissed",
  "Year": "1999",
  "Rated": "PG-13",
  "Released": "09 Apr 1999",
  "Runtime": "107 min",
  "Genre": "Comedy, Drama, Romance",
  "Director": "Raja Gosnell",
  "Writer": "Abby Kohn, Marc Silverstein",
  "Actors": "Drew Barrymore, David Arquette, Michael Vartan, Molly Shannon",
  "Plot": "A journalist enrolls in her old highschool as part of her research for a story.",
  "Language": "English",
  "Country": "USA",
  "Awards": "2 wins & 8 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTQyODI1Njg3Ml5BMl5BanBnXkFtZTcwNTI0MDcyMQ@@._V1_SX300.jpg",
  "Metascore": "60",
  "imdbRating": "6.0",
  "imdbVotes": "60,406",
  "imdbID": "tt0151738",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "The Great Gatsby",
  "Year": "2013",
  "Rated": "PG-13",
  "Released": "10 May 2013",
  "Runtime": "143 min",
  "Genre": "Drama, Romance",
  "Director": "Baz Luhrmann",
  "Writer": "Baz Luhrmann (screenplay), Craig Pearce (screenplay), F. Scott Fitzgerald (based on the novel by)",
  "Actors": "Lisa Adam, Frank Aldridge, Amitabh Bachchan, Steve Bisley",
  "Plot": "A Midwestern war veteran finds himself drawn to the past and lifestyle of his millionaire neighbor.",
  "Language": "English",
  "Country": "Australia, USA",
  "Awards": "Won 2 Oscars. Another 43 wins & 60 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTkxNTk1ODcxNl5BMl5BanBnXkFtZTcwMDI1OTMzOQ@@._V1_SX300.jpg",
  "Metascore": "55",
  "imdbRating": "7.3",
  "imdbVotes": "285,586",
  "imdbID": "tt1343092",
  "Type": "movie",
  "Response": "True"
}

// Nostalgic
// You should’ve been alive in the 40’s when everyone was witty
{
  "Title": "The Maltese Falcon",
  "Year": "1941",
  "Rated": "Not Rated",
  "Released": "18 Oct 1941",
  "Runtime": "100 min",
  "Genre": "Drama, Film-Noir, Mystery",
  "Director": "John Huston",
  "Writer": "John Huston (screenplay), Dashiell Hammett (based upon the novel by)",
  "Actors": "Humphrey Bogart, Mary Astor, Gladys George, Peter Lorre",
  "Plot": "A private detective takes on a case that involves him with three eccentric criminals, a gorgeous liar, and their quest for a priceless statuette.",
  "Language": "English",
  "Country": "USA",
  "Awards": "Nominated for 3 Oscars. Another 2 wins.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTc4MDEzOTMwMl5BMl5BanBnXkFtZTgwMTc2NjgyMjE@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "8.2",
  "imdbVotes": "94,255",
  "imdbID": "tt0033870",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Citizen Kane",
  "Year": "1941",
  "Rated": "Approved",
  "Released": "05 Sep 1941",
  "Runtime": "119 min",
  "Genre": "Drama, Mystery",
  "Director": "Orson Welles",
  "Writer": "Herman J. Mankiewicz (original screen play), Orson Welles (original screen play)",
  "Actors": "Joseph Cotten, Dorothy Comingore, Agnes Moorehead, Ruth Warrick",
  "Plot": "Following the death of a publishing tycoon, news reporters scramble to discover the meaning of his final utterance.",
  "Language": "English",
  "Country": "USA",
  "Awards": "Won 1 Oscar. Another 8 wins & 10 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTQ2Mjc1MDQwMl5BMl5BanBnXkFtZTcwNzUyOTUyMg@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "8.4",
  "imdbVotes": "252,413",
  "imdbID": "tt0033467",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Miracle on 34th Street",
  "Year": "1947",
  "Rated": "Approved",
  "Released": "02 May 1947",
  "Runtime": "96 min",
  "Genre": "Comedy, Drama, Family",
  "Director": "George Seaton",
  "Writer": "George Seaton (written for the screen by), Valentine Davies (story)",
  "Actors": "Maureen O'Hara, John Payne, Edmund Gwenn, Gene Lockhart",
  "Plot": "When a nice old man who claims to be Santa Claus is institutionalized as insane, a young lawyer decides to defend him by arguing in court that he is the real thing.",
  "Language": "English, Dutch",
  "Country": "USA",
  "Awards": "Won 3 Oscars. Another 4 wins & 1 nomination.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTcyNDIyMjc0MF5BMl5BanBnXkFtZTcwOTcxNTkzMQ@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "7.9",
  "imdbVotes": "26,825",
  "imdbID": "tt0039628",
  "Type": "movie",
  "Response": "True"
}

// You haven’t been happy since you were 12
{
  "Title": "Stand by Me",
  "Year": "1986",
  "Rated": "R",
  "Released": "22 Aug 1986",
  "Runtime": "89 min",
  "Genre": "Adventure, Drama",
  "Director": "Rob Reiner",
  "Writer": "Stephen King (novel), Raynold Gideon (screenplay), Bruce A. Evans (screenplay)",
  "Actors": "Wil Wheaton, River Phoenix, Corey Feldman, Jerry O'Connell",
  "Plot": "After the death of a friend, a writer recounts a boyhood journey to find the body of a missing boy.",
  "Language": "English",
  "Country": "USA",
  "Awards": "Nominated for 1 Oscar. Another 3 wins & 10 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BNDk2MTkyMTA1OF5BMl5BanBnXkFtZTcwOTc2Njk3OA@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "8.1",
  "imdbVotes": "222,025",
  "imdbID": "tt0092005",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "The Outsiders",
  "Year": "1983",
  "Rated": "PG-13",
  "Released": "25 Mar 1983",
  "Runtime": "91 min",
  "Genre": "Crime, Drama",
  "Director": "Francis Ford Coppola",
  "Writer": "Kathleen Rowell (screenplay), S.E. Hinton (novel)",
  "Actors": "C. Thomas Howell, Matt Dillon, Ralph Macchio, Patrick Swayze",
  "Plot": "The rivalry between two gangs, the poor Greasers and the rich Socs, only heats up when one gang member kills a member of the other.",
  "Language": "English",
  "Country": "USA",
  "Awards": "1 win & 3 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTcxMDQ0OTM3OV5BMl5BanBnXkFtZTYwNTkxODI5._V1._CR24,22,273,428_SX89_AL_.jpg_V1_SX300.jpg",
  "Metascore": "38",
  "imdbRating": "7.2",
  "imdbVotes": "49,885",
  "imdbID": "tt0086066",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "The Goonies",
  "Year": "1985",
  "Rated": "PG",
  "Released": "07 Jun 1985",
  "Runtime": "114 min",
  "Genre": "Adventure, Comedy, Family",
  "Director": "Richard Donner",
  "Writer": "Steven Spielberg (story), Chris Columbus (screenplay)",
  "Actors": "Sean Astin, Josh Brolin, Jeff Cohen, Corey Feldman",
  "Plot": "In order to save their home from foreclosure, a group of misfits set out to find a pirate's ancient treasure.",
  "Language": "English, Spanish, Cantonese, Italian",
  "Country": "USA",
  "Awards": "2 wins & 6 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTEyMzM3NDQyMjJeQTJeQWpwZ15BbWU4MDE4ODY0NjEx._V1_SX300.jpg",
  "Metascore": "60",
  "imdbRating": "7.8",
  "imdbVotes": "149,448",
  "imdbID": "tt0089218",
  "Type": "movie",
  "Response": "True"
}

// Sappy
// The right person will enter your life in the form of a hotel maid
{
  "Title": "Maid in Manhattan",
  "Year": "2002",
  "Rated": "PG-13",
  "Released": "13 Dec 2002",
  "Runtime": "105 min",
  "Genre": "Comedy, Drama, Romance",
  "Director": "Wayne Wang",
  "Writer": "John Hughes (story), Kevin Wade (screenplay)",
  "Actors": "Jennifer Lopez, Ralph Fiennes, Natasha Richardson, Stanley Tucci",
  "Plot": "A senatorial candidate falls for a hotel maid, thinking she is a socialite when he sees her trying on a wealthy woman's dress.",
  "Language": "English, French, Spanish",
  "Country": "USA",
  "Awards": "8 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTczODg2ODI2M15BMl5BanBnXkFtZTYwODIxMDg5._V1_SX300.jpg",
  "Metascore": "45",
  "imdbRating": "4.9",
  "imdbVotes": "59,602",
  "imdbID": "tt0252076",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Blue Crush",
  "Year": "2002",
  "Rated": "PG-13",
  "Released": "16 Aug 2002",
  "Runtime": "104 min",
  "Genre": "Drama, Romance, Sport",
  "Director": "John Stockwell",
  "Writer": "Susan Orlean (magazine article \"Surf Girls of Maui\"), Lizzy Weiss (story), Lizzy Weiss (screenplay), John Stockwell (screenplay)",
  "Actors": "Kate Bosworth, Matthew Davis, Michelle Rodriguez, Sanoe Lake",
  "Plot": "As a hard-core surfer girl prepares for a big competition, she finds herself falling for a football player.",
  "Language": "English",
  "Country": "USA, Germany",
  "Awards": "1 win & 6 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTY0NDU0ODIzNl5BMl5BanBnXkFtZTYwMDgxMzg5._V1_SX300.jpg",
  "Metascore": "61",
  "imdbRating": "5.6",
  "imdbVotes": "23,644",
  "imdbID": "tt0300532",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Forgetting Sarah Marshall",
  "Year": "2008",
  "Rated": "R",
  "Released": "18 Apr 2008",
  "Runtime": "111 min",
  "Genre": "Comedy, Drama, Romance",
  "Director": "Nicholas Stoller",
  "Writer": "Jason Segel",
  "Actors": "Jason Segel, Kristen Bell, Mila Kunis, Russell Brand",
  "Plot": "Devastated Peter takes a Hawaiian vacation in order to deal with the recent break-up with his TV star girlfriend, Sarah. Little does he know, Sarah's traveling to the same resort as her ex - and she's bringing along her new boyfriend.",
  "Language": "English, Hawaiian, German, Japanese",
  "Country": "USA",
  "Awards": "2 wins & 13 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTYzODgzMjAyM15BMl5BanBnXkFtZTcwMTI3NzI2MQ@@._V1_SX300.jpg",
  "Metascore": "67",
  "imdbRating": "7.2",
  "imdbVotes": "191,892",
  "imdbID": "tt0800039",
  "Type": "movie",
  "Response": "True"
}

// It’s Valentine’s Day and I’m alone
{
  "Title": "Requiem for a Dream",
  "Year": "2000",
  "Rated": "R",
  "Released": "27 Oct 2000",
  "Runtime": "102 min",
  "Genre": "Drama",
  "Director": "Darren Aronofsky",
  "Writer": "Hubert Selby Jr. (based on the book by), Hubert Selby Jr. (screenplay), Darren Aronofsky (screenplay)",
  "Actors": "Ellen Burstyn, Jared Leto, Jennifer Connelly, Marlon Wayans",
  "Plot": "The drug-induced utopias of four Coney Island people are shattered when their addictions become stronger.",
  "Language": "English",
  "Country": "USA",
  "Awards": "Nominated for 1 Oscar. Another 32 wins & 47 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMzM2OTYwMTY4Nl5BMl5BanBnXkFtZTcwMjU1Njg3OA@@._V1_SX300.jpg",
  "Metascore": "68",
  "imdbRating": "8.4",
  "imdbVotes": "473,193",
  "imdbID": "tt0180093",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Fatal Attraction",
  "Year": "1987",
  "Rated": "R",
  "Released": "18 Sep 1987",
  "Runtime": "119 min",
  "Genre": "Drama, Thriller",
  "Director": "Adrian Lyne",
  "Writer": "James Dearden (screenplay), James Dearden (short film)",
  "Actors": "Michael Douglas, Glenn Close, Anne Archer, Ellen Hamilton Latzen",
  "Plot": "A married man's one night stand comes back to haunt him when that lover begins to stalk him and his family.",
  "Language": "English",
  "Country": "USA",
  "Awards": "Nominated for 6 Oscars. Another 7 wins & 16 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTcyODA3NjcxMl5BMl5BanBnXkFtZTcwOTY1NTk3OA@@._V1_SX300.jpg",
  "Metascore": "67",
  "imdbRating": "6.9",
  "imdbVotes": "47,011",
  "imdbID": "tt0093010",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "My Bloody Valentine",
  "Year": "2009",
  "Rated": "R",
  "Released": "16 Jan 2009",
  "Runtime": "101 min",
  "Genre": "Horror, Mystery",
  "Director": "Patrick Lussier",
  "Writer": "Todd Farmer (screenplay), Zane Smith (screenplay), John Beaird, Stephen A. Miller",
  "Actors": "Jensen Ackles, Jaime King, Kerr Smith, Betsy Rue",
  "Plot": "Tom returns to his hometown on the tenth anniversary of the Valentine's night massacre that claimed the lives of 22 people. Instead of a homecoming, however, Tom finds himself suspected of committing the murders, and it seems like his old flame is the only one will believes he's innocent.",
  "Language": "English",
  "Country": "USA",
  "Awards": "1 nomination.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTY2MTQ1OTcxOF5BMl5BanBnXkFtZTcwMjc2ODUxMg@@._V1_SX300.jpg",
  "Metascore": "51",
  "imdbRating": "5.5",
  "imdbVotes": "41,221",
  "imdbID": "tt1179891",
  "Type": "movie",
  "Response": "True"
}

//
// Heartbroken
// It’s OK, all you need is your dog. But he’ll die soon.
{
  "Title": "My Dog Skip",
  "Year": "2000",
  "Rated": "PG",
  "Released": "03 Mar 2000",
  "Runtime": "95 min",
  "Genre": "Drama, Family, Sport",
  "Director": "Jay Russell",
  "Writer": "Willie Morris (book), Gail Gilchriest (screenplay)",
  "Actors": "Frankie Muniz, Diane Lane, Luke Wilson, Kevin Bacon",
  "Plot": "A shy boy grows up in 1940s Mississippi with the help of his beloved dog, Skip.",
  "Language": "English, German",
  "Country": "USA",
  "Awards": "6 wins & 4 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTc1NDgxMjg5MV5BMl5BanBnXkFtZTYwNTUxODc5._V1_SX300.jpg",
  "Metascore": "61",
  "imdbRating": "7.0",
  "imdbVotes": "15,367",
  "imdbID": "tt0156812",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Marley & Me",
  "Year": "2008",
  "Rated": "PG",
  "Released": "25 Dec 2008",
  "Runtime": "115 min",
  "Genre": "Comedy, Drama, Family",
  "Director": "David Frankel",
  "Writer": "Scott Frank (screenplay), Don Roos (screenplay), John Grogan (book)",
  "Actors": "Owen Wilson, Jennifer Aniston, Eric Dane, Kathleen Turner",
  "Plot": "A family learns important life lessons from their adorable, but naughty and neurotic dog.",
  "Language": "English",
  "Country": "USA",
  "Awards": "2 wins & 4 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BNTU1OTg1MTc3OV5BMl5BanBnXkFtZTcwMjI0OTc5MQ@@._V1_SX300.jpg",
  "Metascore": "53",
  "imdbRating": "7.1",
  "imdbVotes": "100,828",
  "imdbID": "tt0822832",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Old Yeller",
  "Year": "1957",
  "Rated": "Approved",
  "Released": "25 Dec 1957",
  "Runtime": "83 min",
  "Genre": "Family, Drama, Adventure",
  "Director": "Robert Stevenson",
  "Writer": "Fred Gipson (screenplay), William Tunberg (screenplay), Fred Gipson (book)",
  "Actors": "Dorothy McGuire, Fess Parker, Jeff York, Chuck Connors",
  "Plot": "A boy brings a yellow dog home. The dog loves the family as much as they love him, but can the love last ?",
  "Language": "English",
  "Country": "USA",
  "Awards": "1 win.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTI2MTcwNjAwNF5BMl5BanBnXkFtZTcwMTYzODAzMQ@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "7.3",
  "imdbVotes": "7,327",
  "imdbID": "tt0050798",
  "Type": "movie",
  "Response": "True"
}

//   What doesn’t kill you will leave you bitter for the rest of your life
{
  "Title": "Falling Down",
  "Year": "1993",
  "Rated": "R",
  "Released": "26 Feb 1993",
  "Runtime": "113 min",
  "Genre": "Crime, Drama, Thriller",
  "Director": "Joel Schumacher",
  "Writer": "Ebbe Roe Smith",
  "Actors": "Michael Douglas, Robert Duvall, Barbara Hershey, Rachel Ticotin",
  "Plot": "An unemployed defense worker frustrated with the various flaws he sees in society, begins to psychotically and violently lash out against them.",
  "Language": "English, Spanish, Korean",
  "Country": "France, USA, UK",
  "Awards": "1 win & 2 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMjA2NTY0MTIyNF5BMl5BanBnXkFtZTYwMTAwMjQ5._V1_SX300.jpg",
  "Metascore": "56",
  "imdbRating": "7.6",
  "imdbVotes": "120,816",
  "imdbID": "tt0106856",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Office Space",
  "Year": "1999",
  "Rated": "R",
  "Released": "19 Feb 1999",
  "Runtime": "89 min",
  "Genre": "Comedy",
  "Director": "Mike Judge",
  "Writer": "Mike Judge (Milton animated shorts), Mike Judge (screenplay)",
  "Actors": "Ron Livingston, Jennifer Aniston, David Herman, Ajay Naidu",
  "Plot": "Three company workers who hate their jobs and decide to rebel against their greedy boss.",
  "Language": "English",
  "Country": "USA",
  "Awards": "2 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BOTA5MzQ3MzI1NV5BMl5BanBnXkFtZTgwNTcxNTYxMTE@._V1_SX300.jpg",
  "Metascore": "68",
  "imdbRating": "7.8",
  "imdbVotes": "177,375",
  "imdbID": "tt0151804",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "The Wrestler",
  "Year": "2008",
  "Rated": "R",
  "Released": "30 Jan 2009",
  "Runtime": "109 min",
  "Genre": "Drama, Sport",
  "Director": "Darren Aronofsky",
  "Writer": "Robert D. Siegel",
  "Actors": "Mickey Rourke, Marisa Tomei, Evan Rachel Wood, Mark Margolis",
  "Plot": "A faded professional wrestler must retire, but finds his quest for a new life outside the ring a dispiriting struggle.",
  "Language": "English",
  "Country": "USA, France",
  "Awards": "Nominated for 2 Oscars. Another 55 wins & 48 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTc5MjYyOTg4MF5BMl5BanBnXkFtZTcwNDc2MzQwMg@@._V1_SX300.jpg",
  "Metascore": "81",
  "imdbRating": "7.9",
  "imdbVotes": "230,890",
  "imdbID": "tt1125849",
  "Type": "movie",
  "Response": "True"
}
//
//   Inspired
//
//   Sporty
//   If you don’t get chill bumps when Rudy makes the sack, try our Lonely category
{
  "Title": "Rudy",
  "Year": "1993",
  "Rated": "PG",
  "Released": "22 Oct 1993",
  "Runtime": "114 min",
  "Genre": "Biography, Drama, Sport",
  "Director": "David Anspaugh",
  "Writer": "Angelo Pizzo",
  "Actors": "Sean Astin, Jon Favreau, Ned Beatty, Greta Lind",
  "Plot": "Rudy has always been told that he was too small to play college football. But he is determined to overcome the odds and fulfill his dream of playing for Notre Dame.",
  "Language": "English, Spanish",
  "Country": "USA",
  "Awards": "2 wins & 1 nomination.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTI1NTc4NjA4M15BMl5BanBnXkFtZTcwNDYwOTgxMQ@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "7.5",
  "imdbVotes": "37,114",
  "imdbID": "tt0108002",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Remember the Titans",
  "Year": "2000",
  "Rated": "PG",
  "Released": "29 Sep 2000",
  "Runtime": "113 min",
  "Genre": "Biography, Drama, Sport",
  "Director": "Boaz Yakin",
  "Writer": "Gregory Allen Howard",
  "Actors": "Denzel Washington, Will Patton, Wood Harris, Ryan Hurst",
  "Plot": "The true story of a newly appointed African-American coach and his high school team on their first season as a racially integrated unit.",
  "Language": "English",
  "Country": "USA",
  "Awards": "7 wins & 17 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTczNTA2MDc0OF5BMl5BanBnXkFtZTYwMTg4MDY2._V1_SX300.jpg",
  "Metascore": "48",
  "imdbRating": "7.7",
  "imdbVotes": "140,092",
  "imdbID": "tt0210945",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "The Blind Side",
  "Year": "2009",
  "Rated": "PG-13",
  "Released": "20 Nov 2009",
  "Runtime": "129 min",
  "Genre": "Biography, Drama, Sport",
  "Director": "John Lee Hancock",
  "Writer": "John Lee Hancock, Michael Lewis (book)",
  "Actors": "Sandra Bullock, Tim McGraw, Quinton Aaron, Jae Head",
  "Plot": "The story of Michael Oher, a homeless and traumatized boy who became an All American football player and first round NFL draft pick with the help of a caring woman and her family.",
  "Language": "English",
  "Country": "USA",
  "Awards": "Won 1 Oscar. Another 7 wins & 27 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMjEzOTE3ODM3OF5BMl5BanBnXkFtZTcwMzYyODI4Mg@@._V1_SX300.jpg",
  "Metascore": "53",
  "imdbRating": "7.7",
  "imdbVotes": "182,091",
  "imdbID": "tt0878804",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "The Mighty Ducks",
  "Year": "1992",
  "Rated": "PG",
  "Released": "02 Oct 1992",
  "Runtime": "100 min",
  "Genre": "Action, Comedy, Drama",
  "Director": "Stephen Herek",
  "Writer": "Steven Brill",
  "Actors": "Emilio Estevez, Joss Ackland, Lane Smith, Heidi Kling",
  "Plot": "A self-centered lawyer is sentenced to community service coaching a rag tag youth hockey team.",
  "Language": "English",
  "Country": "USA",
  "Awards": "2 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTIzMzgxOTQwMV5BMl5BanBnXkFtZTcwMzkzNDYyMQ@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "6.4",
  "imdbVotes": "37,974",
  "imdbID": "tt0104868",
  "Type": "movie",
  "Response": "True"
}


//   The theme music alone will make you feel invincible
{
  "Title": "Rocky",
  "Year": "1976",
  "Rated": "PG",
  "Released": "03 Dec 1976",
  "Runtime": "119 min",
  "Genre": "Drama, Sport",
  "Director": "John G. Avildsen",
  "Writer": "Sylvester Stallone",
  "Actors": "Sylvester Stallone, Talia Shire, Burt Young, Carl Weathers",
  "Plot": "Rocky Balboa, a small-time boxer gets a supremely rare chance to fight the heavy-weight champion, Apollo Creed, in a bout in which he strives to go the distance for his self-respect.",
  "Language": "English",
  "Country": "USA",
  "Awards": "Won 3 Oscars. Another 17 wins & 20 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTY5MDMzODUyOF5BMl5BanBnXkFtZTcwMTQ3NTMyNA@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "8.1",
  "imdbVotes": "285,958",
  "imdbID": "tt0075148",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Hoosiers",
  "Year": "1986",
  "Rated": "PG",
  "Released": "27 Feb 1987",
  "Runtime": "114 min",
  "Genre": "Drama, Sport",
  "Director": "David Anspaugh",
  "Writer": "Angelo Pizzo",
  "Actors": "Gene Hackman, Barbara Hershey, Dennis Hopper, Sheb Wooley",
  "Plot": "A coach with a checkered past and a local drunk train a small town high school basketball team to become a top contender for the championship.",
  "Language": "English",
  "Country": "UK, USA",
  "Awards": "Nominated for 2 Oscars. Another 3 wins & 3 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTYyNTc0OTUwNV5BMl5BanBnXkFtZTcwODA3NzE0NA@@._V1_SX300.jpg",
  "Metascore": "76",
  "imdbRating": "7.6",
  "imdbVotes": "30,349",
  "imdbID": "tt0091217",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Space Jam",
  "Year": "1996",
  "Rated": "PG",
  "Released": "15 Nov 1996",
  "Runtime": "88 min",
  "Genre": "Animation, Adventure, Comedy",
  "Director": "Joe Pytka",
  "Writer": "Leo Benvenuti, Steve Rudnick, Timothy Harris, Herschel Weingrod",
  "Actors": "Michael Jordan, Wayne Knight, Theresa Randle, Manner Washington",
  "Plot": "Michael Jordan agrees to help the Looney Toons play a basketball game vs. alien slavers to determine their freedom.",
  "Language": "English",
  "Country": "USA",
  "Awards": "5 wins & 6 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTQ5NDg1NTgwOV5BMl5BanBnXkFtZTcwODAwNDAwMQ@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "6.2",
  "imdbVotes": "87,154",
  "imdbID": "tt0117705",
  "Type": "movie",
  "Response": "True"
}
//   Intense
//
//   The more of an asshole you are, the more likely you are to make history
{
  "Title": "Aviator",
  "Year": "2005",
  "Rated": "N/A",
  "Released": "10 Jan 2005",
  "Runtime": "22 min",
  "Genre": "Family, News",
  "Director": "Nancy Criss",
  "Writer": "N/A",
  "Actors": "Nancy Criss, Leonardo DiCaprio, Doris Roberts, Martin Scorsese",
  "Plot": "N/A",
  "Language": "N/A",
  "Country": "N/A",
  "Awards": "N/A",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMjE2OTQxNzY4OF5BMl5BanBnXkFtZTcwOTc2MDIzMQ@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "8.1",
  "imdbVotes": "51",
  "imdbID": "tt0666621",
  "Type": "episode",
  "Response": "True"
},
{
  "Title": "J. Edgar",
  "Year": "2011",
  "Rated": "R",
  "Released": "11 Nov 2011",
  "Runtime": "137 min",
  "Genre": "Biography, Crime, Drama",
  "Director": "Clint Eastwood",
  "Writer": "Dustin Lance Black",
  "Actors": "Leonardo DiCaprio, Josh Hamilton, Geoff Pierson, Cheryl Lawson",
  "Plot": "J. Edgar Hoover, powerful head of the F.B.I. for nearly 50 years, looks back on his professional and personal life.",
  "Language": "English",
  "Country": "USA",
  "Awards": "Nominated for 1 Golden Globe. Another 5 wins & 15 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTc0NDM4ODU2Nl5BMl5BanBnXkFtZTcwNzQ0NTg4Ng@@._V1_SX300.jpg",
  "Metascore": "59",
  "imdbRating": "6.6",
  "imdbVotes": "88,688",
  "imdbID": "tt1616195",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Catch Me If You Can",
  "Year": "2002",
  "Rated": "PG-13",
  "Released": "25 Dec 2002",
  "Runtime": "141 min",
  "Genre": "Biography, Crime, Drama",
  "Director": "Steven Spielberg",
  "Writer": "Jeff Nathanson (screenplay), Frank Abagnale Jr. (book), Stan Redding (book)",
  "Actors": "Leonardo DiCaprio, Tom Hanks, Christopher Walken, Martin Sheen",
  "Plot": "A true story about Frank Abagnale Jr., who, before his 19th birthday, successfully conned millions of dollars' worth of checks as a Pan Am pilot, doctor, and legal prosecutor.",
  "Language": "English, French",
  "Country": "USA, Canada",
  "Awards": "Nominated for 2 Oscars. Another 13 wins & 24 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTY5MzYzNjc5NV5BMl5BanBnXkFtZTYwNTUyNTc2._V1_SX300.jpg",
  "Metascore": "76",
  "imdbRating": "8.0",
  "imdbVotes": "398,722",
  "imdbID": "tt0264464",
  "Type": "movie",
  "Response": "True"
}
//   You’ll survive prison if your jawline is strong enough
{
  "Title": "Escape from Alcatraz",
  "Year": "1979",
  "Rated": "PG",
  "Released": "22 Jun 1979",
  "Runtime": "112 min",
  "Genre": "Action, Biography, Crime",
  "Director": "Don Siegel",
  "Writer": "J. Campbell Bruce (book), Richard Tuggle (screenplay)",
  "Actors": "Clint Eastwood, Patrick McGoohan, Roberts Blossom, Jack Thibeau",
  "Plot": "A dramatization of the one possibly successful escape from the infamous prison island in 1962.",
  "Language": "English",
  "Country": "USA",
  "Awards": "N/A",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMjY4ODYxOTYyOV5BMl5BanBnXkFtZTgwNzczNjQxMTE@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "7.6",
  "imdbVotes": "74,798",
  "imdbID": "tt0079116",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "The Great Escape",
  "Year": "1963",
  "Rated": "Unrated",
  "Released": "04 Jul 1963",
  "Runtime": "172 min",
  "Genre": "Adventure, Drama, History",
  "Director": "John Sturges",
  "Writer": "Paul Brickhill (book), James Clavell (screenplay), W.R. Burnett (screenplay)",
  "Actors": "Steve McQueen, James Garner, Richard Attenborough, James Donald",
  "Plot": "Allied P.O.W.s plan for several hundred of their number to escape from a German camp during World War II.",
  "Language": "English, German, French, Russian",
  "Country": "USA",
  "Awards": "Nominated for 1 Oscar. Another 4 wins & 4 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMjI2MTQwNDI3Nl5BMl5BanBnXkFtZTcwNDk4MTkzNA@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "8.3",
  "imdbVotes": "134,891",
  "imdbID": "tt0057115",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Victory",
  "Year": "1981",
  "Rated": "PG",
  "Released": "30 Jul 1981",
  "Runtime": "116 min",
  "Genre": "Action, Drama, Sport",
  "Director": "John Huston",
  "Writer": "Yabo Yablonsky (story), Djordje Milicevic (story), Jeff Maguire (story), Evan Jones (screenplay), Yabo Yablonsky (screenplay)",
  "Actors": "Sylvester Stallone, Michael Caine, Pelé, Bobby Moore",
  "Plot": "As allied POWs prepare for a soccer game against the German National Team to be played in Nazi-occupied Paris, the French Resistance and British officers are making plans for the team's escape.",
  "Language": "English",
  "Country": "USA",
  "Awards": "1 nomination.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTY5MTYwODI1MV5BMl5BanBnXkFtZTcwNDEyMDkxMQ@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "6.6",
  "imdbVotes": "17,922",
  "imdbID": "tt0083284",
  "Type": "movie",
  "Response": "True"
}
//
//   Intelligent
//   If you hear voices in your head, you might be a genius
{
  "Title": "A Beautiful Mind",
  "Year": "2001",
  "Rated": "PG-13",
  "Released": "04 Jan 2002",
  "Runtime": "135 min",
  "Genre": "Biography, Drama",
  "Director": "Ron Howard",
  "Writer": "Akiva Goldsman, Sylvia Nasar (book)",
  "Actors": "Russell Crowe, Ed Harris, Jennifer Connelly, Christopher Plummer",
  "Plot": "After a brilliant but asocial mathematician accepts secret work in cryptography, his life takes a turn for the nightmarish.",
  "Language": "English",
  "Country": "USA",
  "Awards": "Won 4 Oscars. Another 30 wins & 54 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTQ4MDI2MzkwMl5BMl5BanBnXkFtZTYwMjk0NTA5._V1_SX300.jpg",
  "Metascore": "72",
  "imdbRating": "8.2",
  "imdbVotes": "470,880",
  "imdbID": "tt0268978",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Good Will Hunting",
  "Year": "1997",
  "Rated": "R",
  "Released": "09 Jan 1998",
  "Runtime": "126 min",
  "Genre": "Drama",
  "Director": "Gus Van Sant",
  "Writer": "Matt Damon, Ben Affleck",
  "Actors": "Matt Damon, Robin Williams, Ben Affleck, Stellan Skarsgård",
  "Plot": "Will Hunting, a janitor at M.I.T., has a gift for mathematics, but needs help from a psychologist to find direction in his life.",
  "Language": "English",
  "Country": "USA",
  "Awards": "Won 2 Oscars. Another 19 wins & 43 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTk0NjY0Mzg5MF5BMl5BanBnXkFtZTcwNzM1OTM2MQ@@._V1_SX300.jpg",
  "Metascore": "70",
  "imdbRating": "8.3",
  "imdbVotes": "488,744",
  "imdbID": "tt0119217",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Rain Man",
  "Year": "1988",
  "Rated": "R",
  "Released": "16 Dec 1988",
  "Runtime": "133 min",
  "Genre": "Drama",
  "Director": "Barry Levinson",
  "Writer": "Barry Morrow (story), Ronald Bass (screenplay), Barry Morrow (screenplay)",
  "Actors": "Dustin Hoffman, Tom Cruise, Valeria Golino, Gerald R. Molen",
  "Plot": "Selfish yuppie Charlie Babbitt's father left a fortune to his savant brother Raymond and a pittance to Charlie; they travel cross-country.",
  "Language": "English, Italian",
  "Country": "USA",
  "Awards": "Won 4 Oscars. Another 22 wins & 19 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTQ4NTA1NDU3NV5BMl5BanBnXkFtZTcwODUwMTU2NA@@._V1_SX300.jpg",
  "Metascore": "65",
  "imdbRating": "8.0",
  "imdbVotes": "341,789",
  "imdbID": "tt0095953",
  "Type": "movie",
  "Response": "True"
}
//   Crack the Nazi code, help end the war, and you’ll end up chemically castrated and suicidal
{
  "Title": "The Imitation Game",
  "Year": "2014",
  "Rated": "PG-13",
  "Released": "25 Dec 2014",
  "Runtime": "114 min",
  "Genre": "Biography, Drama, Thriller",
  "Director": "Morten Tyldum",
  "Writer": "Andrew Hodges (book), Graham Moore (screenplay)",
  "Actors": "Benedict Cumberbatch, Keira Knightley, Matthew Goode, Rory Kinnear",
  "Plot": "During World War II, mathematician Alan Turing tries to crack the enigma code with help from fellow mathematicians.",
  "Language": "English",
  "Country": "UK, USA",
  "Awards": "Nominated for 8 Oscars. Another 39 wins & 96 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BNDkwNTEyMzkzNl5BMl5BanBnXkFtZTgwNTAwNzk3MjE@._V1_SX300.jpg",
  "Metascore": "72",
  "imdbRating": "8.2",
  "imdbVotes": "91,852",
  "imdbID": "tt2084970",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Dead Snow",
  "Year": "2009",
  "Rated": "Not Rated",
  "Released": "09 Jan 2009",
  "Runtime": "91 min",
  "Genre": "Comedy, Horror",
  "Director": "Tommy Wirkola",
  "Writer": "Tommy Wirkola, Stig Frode Henriksen",
  "Actors": "Vegar Hoel, Stig Frode Henriksen, Charlotte Frogner, Lasse Valdal",
  "Plot": "A ski vacation turns horrific for a group of medical students, as they find themselves confronted by an unimaginable menace: Nazi zombies.",
  "Language": "Norwegian",
  "Country": "Norway",
  "Awards": "1 win.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMjA0NDQyMjE1MF5BMl5BanBnXkFtZTcwODE1NzY5MQ@@._V1_SX300.jpg",
  "Metascore": "61",
  "imdbRating": "6.4",
  "imdbVotes": "46,852",
  "imdbID": "tt1278340",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Inglourious Basterds",
  "Year": "2009",
  "Rated": "R",
  "Released": "21 Aug 2009",
  "Runtime": "153 min",
  "Genre": "Adventure, Drama, War",
  "Director": "Quentin Tarantino, Eli Roth",
  "Writer": "Quentin Tarantino",
  "Actors": "Brad Pitt, Mélanie Laurent, Christoph Waltz, Eli Roth",
  "Plot": "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.",
  "Language": "English, German, French, Italian",
  "Country": "USA, Germany",
  "Awards": "Won 1 Oscar. Another 121 wins & 99 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMjIzMDI4MTUzOV5BMl5BanBnXkFtZTcwNDY3NjA3Mg@@._V1_SX300.jpg",
  "Metascore": "69",
  "imdbRating": "8.3",
  "imdbVotes": "667,399",
  "imdbID": "tt0361748",
  "Type": "movie",
  "Response": "True"
}
//
//   Creative
{
  "Title": "Pollock",
  "Year": "2000",
  "Rated": "R",
  "Released": "18 May 2001",
  "Runtime": "122 min",
  "Genre": "Biography, Drama",
  "Director": "Ed Harris",
  "Writer": "Steven Naifeh (book), Gregory White Smith (book), Barbara Turner (screenplay), Susan Emshwiller (screenplay)",
  "Actors": "Ed Harris, Marcia Gay Harden, Tom Bower, Jennifer Connelly",
  "Plot": "A film about the life and career of the American painter, Jackson Pollock.",
  "Language": "English",
  "Country": "USA",
  "Awards": "Won 1 Oscar. Another 3 wins & 6 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTM0MjU3NTM5OF5BMl5BanBnXkFtZTcwMDkxODAwMQ@@._V1_SX300.jpg",
  "Metascore": "77",
  "imdbRating": "7.0",
  "imdbVotes": "21,138",
  "imdbID": "tt0183659",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Who the #$&% Is Jackson Pollock?",
  "Year": "2006",
  "Rated": "PG-13",
  "Released": "09 Nov 2006",
  "Runtime": "74 min",
  "Genre": "Documentary",
  "Director": "Harry Moses",
  "Writer": "Harry Moses",
  "Actors": "Teri Horton, Tod M. Volpe, Ben Heller, Nick Carone",
  "Plot": "In this documentary, veteran filmmaker Harry Moses exposes the controversy in the world of high priced artwork. He paints a vivid picture of how art is bought and sold in America.",
  "Language": "English",
  "Country": "USA",
  "Awards": "N/A",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTcyMTQ1Mzk1OV5BMl5BanBnXkFtZTcwMDM3OTY0MQ@@._V1_SX300.jpg",
  "Metascore": "70",
  "imdbRating": "7.1",
  "imdbVotes": "962",
  "imdbID": "tt0487092",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Girl with a Pearl Earring",
  "Year": "2003",
  "Rated": "PG-13",
  "Released": "09 Jan 2004",
  "Runtime": "100 min",
  "Genre": "Biography, Drama, Romance",
  "Director": "Peter Webber",
  "Writer": "Tracy Chevalier (novel), Olivia Hetreed (screenplay)",
  "Actors": "Colin Firth, Scarlett Johansson, Tom Wilkinson, Judy Parfitt",
  "Plot": "A young peasant maid working in the house of painter Johannes Vermeer becomes his talented assistant and the model for one of his most famous works.",
  "Language": "English",
  "Country": "UK, Luxembourg",
  "Awards": "Nominated for 3 Oscars. Another 17 wins & 38 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTU4NjU3NjA0N15BMl5BanBnXkFtZTcwNjI4MTQyMQ@@._V1_SX300.jpg",
  "Metascore": "72",
  "imdbRating": "7.0",
  "imdbVotes": "53,493",
  "imdbID": "tt0335119",
  "Type": "movie",
  "Response": "True"
}
//
//   You’re not really creative unless you hurt yourself
{
  "Title": "Lust for Life",
  "Year": "1956",
  "Rated": "N/A",
  "Released": "15 Sep 1956",
  "Runtime": "122 min",
  "Genre": "Biography, Drama",
  "Director": "Vincente Minnelli, George Cukor",
  "Writer": "Norman Corwin (screen play), Irving Stone (based on the novel by)",
  "Actors": "Kirk Douglas, Anthony Quinn, James Donald, Pamela Brown",
  "Plot": "The life of brilliant but tortured artist Vincent van Gogh.",
  "Language": "English",
  "Country": "USA",
  "Awards": "Won 1 Oscar. Another 3 wins & 6 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BNzczMzA2NDkwNF5BMl5BanBnXkFtZTcwNjUzMjk3OA@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "7.4",
  "imdbVotes": "6,204",
  "imdbID": "tt0049456",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Frida",
  "Year": "2002",
  "Rated": "R",
  "Released": "22 Nov 2002",
  "Runtime": "123 min",
  "Genre": "Biography, Drama, Romance",
  "Director": "Julie Taymor",
  "Writer": "Hayden Herrera (book), Clancy Sigal (screenplay), Diane Lake (screenplay), Gregory Nava (screenplay), Anna Thomas (screenplay)",
  "Actors": "Salma Hayek, Mía Maestro, Alfred Molina, Antonio Banderas",
  "Plot": "A biography of artist Frida Kahlo, who channeled the pain of a crippling injury and her tempestuous marriage into her work.",
  "Language": "English, French, Russian",
  "Country": "USA, Canada, Mexico",
  "Awards": "Won 2 Oscars. Another 17 wins & 33 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTMyODUyMDY1OV5BMl5BanBnXkFtZTYwMDA2OTU3._V1_SX300.jpg",
  "Metascore": "61",
  "imdbRating": "7.4",
  "imdbVotes": "53,306",
  "imdbID": "tt0120679",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Van Gogh",
  "Year": "1991",
  "Rated": "R",
  "Released": "30 Oct 1992",
  "Runtime": "158 min",
  "Genre": "Biography, Drama",
  "Director": "Maurice Pialat",
  "Writer": "Maurice Pialat",
  "Actors": "Jacques Dutronc, Alexandra London, Bernard Le Coq, Gérard Séty",
  "Plot": "The final 67 days of Van Gogh's life is examined.",
  "Language": "French",
  "Country": "France",
  "Awards": "2 wins & 12 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTM0MzcwNjYxN15BMl5BanBnXkFtZTcwNDY5NzAzMQ@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "7.3",
  "imdbVotes": "1,556",
  "imdbID": "tt0103190",
  "Type": "movie",
  "Response": "True"
}
//
//
//   Dark
//
//   Cynical
//   You’re 26 and going through a midlife crisis (
{
  "Title": "Girl Most Likely",
  "Year": "2012",
  "Rated": "PG-13",
  "Released": "18 Jul 2013",
  "Runtime": "103 min",
  "Genre": "Comedy",
  "Director": "Shari Springer Berman, Robert Pulcini",
  "Writer": "Michelle Morgan",
  "Actors": "Kristen Wiig, Annette Bening, Matt Dillon, Darren Criss",
  "Plot": "A failed New York playwright awkwardly navigates the transition from Next Big Thing to Last Year's News.",
  "Language": "English, Romanian",
  "Country": "USA",
  "Awards": "N/A",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTEyMDgyNDYwNjReQTJeQWpwZ15BbWU3MDc1MDQwNjk@._V1_SX300.jpg",
  "Metascore": "38",
  "imdbRating": "5.7",
  "imdbVotes": "9,533",
  "imdbID": "tt1698648",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Tiny Furniture",
  "Year": "2010",
  "Rated": "Not Rated",
  "Released": "30 Mar 2012",
  "Runtime": "98 min",
  "Genre": "Comedy, Drama",
  "Director": "Lena Dunham",
  "Writer": "Lena Dunham",
  "Actors": "Lena Dunham, Laurie Simmons, Grace Dunham, Rachel Howe",
  "Plot": "About a recent college grad who returns home while she tries to figure out what to do with her life.",
  "Language": "English",
  "Country": "USA",
  "Awards": "3 wins & 5 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BNjIzODg0NDY5Nl5BMl5BanBnXkFtZTcwMDQyMzk5Mw@@._V1_SX300.jpg",
  "Metascore": "72",
  "imdbRating": "6.3",
  "imdbVotes": "9,346",
  "imdbID": "tt1570989",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "The Graduate",
  "Year": "1967",
  "Rated": "Approved",
  "Released": "22 Dec 1967",
  "Runtime": "106 min",
  "Genre": "Comedy, Drama, Romance",
  "Director": "Mike Nichols",
  "Writer": "Calder Willingham (screenplay), Buck Henry (screenplay), Charles Webb (based on the novel by)",
  "Actors": "Anne Bancroft, Dustin Hoffman, Katharine Ross, William Daniels",
  "Plot": "Recent college graduate Benjamin Braddock is trapped into an affair with Mrs. Robinson, who happens to be the wife of his father's business partner and then finds himself falling in love with her daughter, Elaine.",
  "Language": "English",
  "Country": "USA",
  "Awards": "Won 1 Oscar. Another 22 wins & 13 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTQ0ODc4MDk4Nl5BMl5BanBnXkFtZTcwMTEzNzgzNA@@._V1_SX300.jpg",
  "Metascore": "77",
  "imdbRating": "8.1",
  "imdbVotes": "180,321",
  "imdbID": "tt0061722",
  "Type": "movie",
  "Response": "True"
}
//     Sarcasm is endearing
{
  "Title": "American Psycho",
  "Year": "2000",
  "Rated": "R",
  "Released": "14 Apr 2000",
  "Runtime": "102 min",
  "Genre": "Crime, Drama",
  "Director": "Mary Harron",
  "Writer": "Bret Easton Ellis (novel), Mary Harron (screenplay), Guinevere Turner (screenplay)",
  "Actors": "Christian Bale, Justin Theroux, Josh Lucas, Bill Sage",
  "Plot": "A wealthy New York investment banking executive hides his alternate psychopathic ego from his co-workers and friends as he escalates deeper into his illogical, gratuitous fantasies.",
  "Language": "English, Spanish, Cantonese",
  "Country": "USA",
  "Awards": "4 wins & 7 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMjIyMTYwMTI0N15BMl5BanBnXkFtZTgwNTU2NTYxMTE@._V1_SX300.jpg",
  "Metascore": "64",
  "imdbRating": "7.6",
  "imdbVotes": "299,369",
  "imdbID": "tt0144084",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "As Good as It Gets",
  "Year": "1997",
  "Rated": "PG-13",
  "Released": "25 Dec 1997",
  "Runtime": "139 min",
  "Genre": "Comedy, Drama, Romance",
  "Director": "James L. Brooks",
  "Writer": "Mark Andrus (story), Mark Andrus (screenplay), James L. Brooks (screenplay)",
  "Actors": "Jack Nicholson, Helen Hunt, Greg Kinnear, Cuba Gooding Jr.",
  "Plot": "A single mother/waitress, a misanthropic author, and a gay artist form an unlikely friendship after the artist is in an accident.",
  "Language": "English",
  "Country": "USA",
  "Awards": "Won 2 Oscars. Another 39 wins & 37 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTc0Nzc5MDEzN15BMl5BanBnXkFtZTcwMjc2NTEyMQ@@._V1_SX300.jpg",
  "Metascore": "67",
  "imdbRating": "7.8",
  "imdbVotes": "203,156",
  "imdbID": "tt0119822",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Die Hard",
  "Year": "1988",
  "Rated": "R",
  "Released": "20 Jul 1988",
  "Runtime": "131 min",
  "Genre": "Action, Thriller",
  "Director": "John McTiernan",
  "Writer": "Roderick Thorp (novel), Jeb Stuart (screenplay), Steven E. de Souza (screenplay)",
  "Actors": "Bruce Willis, Bonnie Bedelia, Reginald VelJohnson, Paul Gleason",
  "Plot": "John McClane, officer of the NYPD, tries to save wife Holly Gennaro and several others, taken hostage by German terrorist Hans Gruber during a Christmas party at the Nakatomi Plaza in Los Angeles.",
  "Language": "English, German, Italian",
  "Country": "USA",
  "Awards": "Nominated for 4 Oscars. Another 6 wins & 2 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTY4ODM0OTc2M15BMl5BanBnXkFtZTcwNzE0MTk3OA@@._V1_SX300.jpg",
  "Metascore": "70",
  "imdbRating": "8.3",
  "imdbVotes": "491,019",
  "imdbID": "tt0095016",
  "Type": "movie",
  "Response": "True"
}
//     Sadistic
//     If its banned, it must be good
{
  "Title": "Salò, or the 120 Days of Sodom",
  "Year": "1975",
  "Rated": "Not Rated",
  "Released": "10 Jan 1976",
  "Runtime": "116 min",
  "Genre": "Drama, War",
  "Director": "Pier Paolo Pasolini",
  "Writer": "Pier Paolo Pasolini, Sergio Citti (screenplay)",
  "Actors": "Paolo Bonacelli, Giorgio Cataldi, Umberto Paolo Quintavalle, Aldo Valletti",
  "Plot": "Four fascist libertines round up nine adolescent boys and girls and subject them to a hundred and twenty days of physical, mental and sexual torture.",
  "Language": "Italian, French, German",
  "Country": "Italy, France",
  "Awards": "N/A",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTQyMDQ4NTY2Nl5BMl5BanBnXkFtZTcwMjk2NDQ3MQ@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "6.0",
  "imdbVotes": "31,674",
  "imdbID": "tt0073650",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "A Clockwork Orange",
  "Year": "1971",
  "Rated": "X",
  "Released": "02 Feb 1972",
  "Runtime": "136 min",
  "Genre": "Crime, Drama, Sci-Fi",
  "Director": "Stanley Kubrick",
  "Writer": "Stanley Kubrick (screenplay), Anthony Burgess (novel)",
  "Actors": "Malcolm McDowell, Patrick Magee, Michael Bates, Warren Clarke",
  "Plot": "In future Britain, charismatic delinquent Alex DeLarge is jailed and volunteers for an experimental aversion therapy developed by the government in an effort to solve society's crime problem - but not all goes according to plan.",
  "Language": "English",
  "Country": "UK, USA",
  "Awards": "Nominated for 4 Oscars. Another 12 wins & 13 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTY3MjM1Mzc4N15BMl5BanBnXkFtZTgwODM0NzAxMDE@._V1_SX300.jpg",
  "Metascore": "78",
  "imdbRating": "8.4",
  "imdbVotes": "448,860",
  "imdbID": "tt0066921",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "A Serbian Film",
  "Year": "2010",
  "Rated": "NC-17",
  "Released": "21 Jan 2012",
  "Runtime": "104 min",
  "Genre": "Horror, Mystery, Thriller",
  "Director": "Srdjan Spasojevic",
  "Writer": "Aleksandar Radivojevic (screenplay), Srdjan Spasojevic (screenplay)",
  "Actors": "Srdjan Todorovic, Sergej Trifunovic, Jelena Gavrilovic, Slobodan Bestic",
  "Plot": "An aging porn star agrees to participate in an \"art film\" in order to make a clean break from the business, only to discover that he has been drafted into making a pedophilia and necrophilia themed snuff film.",
  "Language": "Serbian, English, Swedish",
  "Country": "Serbia",
  "Awards": "1 win & 2 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTU2NzI3OTk4M15BMl5BanBnXkFtZTcwMTEyNzIxNA@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "5.3",
  "imdbVotes": "29,577",
  "imdbID": "tt1273235",
  "Type": "movie",
  "Response": "True"
}
//
//     You better chop them up or eat them whole
{
  "Title": "The Texas Chain Saw Massacre",
  "Year": "1974",
  "Rated": "R",
  "Released": "01 Oct 1974",
  "Runtime": "83 min",
  "Genre": "Horror, Thriller",
  "Director": "Tobe Hooper",
  "Writer": "Kim Henkel (story), Tobe Hooper (story)",
  "Actors": "Marilyn Burns, Allen Danziger, Paul A. Partain, William Vail",
  "Plot": "Five friends visiting their grandfather's house in the country are hunted and terrorized by a chain-saw wielding killer and his family of grave-robbing cannibals.",
  "Language": "English",
  "Country": "USA",
  "Awards": "1 win.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMjA0NDQ2MzMxMF5BMl5BanBnXkFtZTgwODg5MTkzMjE@._V1_SX300.jpg",
  "Metascore": "75",
  "imdbRating": "7.5",
  "imdbVotes": "81,439",
  "imdbID": "tt0072271",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Saw",
  "Year": "2004",
  "Rated": "R",
  "Released": "29 Oct 2004",
  "Runtime": "103 min",
  "Genre": "Horror, Mystery",
  "Director": "James Wan",
  "Writer": "Leigh Whannell, James Wan (story), Leigh Whannell (story)",
  "Actors": "Leigh Whannell, Cary Elwes, Danny Glover, Ken Leung",
  "Plot": "With a dead body lying between them, two men wake up in the secure lair of a serial killer who's been nicknamed \"Jigsaw\". The men must follow various rules and objectives if they wish to survive and win the deadly game set for them.",
  "Language": "English",
  "Country": "USA, Australia",
  "Awards": "6 wins & 8 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMjAyNTcxNzYwMV5BMl5BanBnXkFtZTgwMzQzNzM5MjE@._V1_SX300.jpg",
  "Metascore": "46",
  "imdbRating": "7.7",
  "imdbVotes": "254,280",
  "imdbID": "tt0387564",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Hannibal",
  "Year": "2001",
  "Rated": "R",
  "Released": "09 Feb 2001",
  "Runtime": "131 min",
  "Genre": "Crime, Drama, Thriller",
  "Director": "Ridley Scott",
  "Writer": "Thomas Harris (novel), David Mamet (screenplay), Steven Zaillian (screenplay)",
  "Actors": "Anthony Hopkins, Julianne Moore, Gary Oldman, Ray Liotta",
  "Plot": "Living in exile, Hannibal Lecter tries to reconnect with now disgraced FBI agent Clarice Starling and finds himself a target for revenge from a powerful victim.",
  "Language": "English, Italian, Japanese",
  "Country": "UK, USA",
  "Awards": "7 wins & 15 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMjA1MDcwNjkwOF5BMl5BanBnXkFtZTgwNjcxNTYxMTE@._V1_SX300.jpg",
  "Metascore": "57",
  "imdbRating": "6.7",
  "imdbVotes": "185,334",
  "imdbID": "tt0212985",
  "Type": "movie",
  "Response": "True"
}
//
//
//     Perverted
//     Incest, adultery and autoerotic asphyxiation, Oh my! (
{
  "Title": "Ken Park",
  "Year": "2002",
  "Rated": "Not Rated",
  "Released": "03 Apr 2003",
  "Runtime": "93 min",
  "Genre": "Drama",
  "Director": "Larry Clark, Edward Lachman",
  "Writer": "Harmony Korine (screenplay), Larry Clark (based on stories and characters by)",
  "Actors": "Adam Chubbuck, James Bullard, Seth Gray, Eddie Daniels",
  "Plot": "Ken Park is about several Californian skateboarders' lives and relationships with and without their parents.",
  "Language": "English",
  "Country": "USA, Netherlands, France",
  "Awards": "2 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTM4NjE1ODc5OF5BMl5BanBnXkFtZTcwOTYzMTYyMQ@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "5.9",
  "imdbVotes": "22,323",
  "imdbID": "tt0209077",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Don Jon",
  "Year": "2013",
  "Rated": "R",
  "Released": "27 Sep 2013",
  "Runtime": "90 min",
  "Genre": "Comedy, Drama, Romance",
  "Director": "Joseph Gordon-Levitt",
  "Writer": "Joseph Gordon-Levitt",
  "Actors": "Joseph Gordon-Levitt, Scarlett Johansson, Julianne Moore, Tony Danza",
  "Plot": "A New Jersey guy dedicated to his family, friends, and church, develops unrealistic expectations from watching porn and works to find happiness and intimacy with his potential true love.",
  "Language": "English",
  "Country": "USA",
  "Awards": "4 wins & 18 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTQxNTc3NDM2MF5BMl5BanBnXkFtZTcwNzQ5NTQ3OQ@@._V1._CR28,28.649993896484375,1271,1991.0000305175781_SX89_AL_.jpg_V1_SX300.jpg",
  "Metascore": "66",
  "imdbRating": "6.7",
  "imdbVotes": "152,538",
  "imdbID": "tt2229499",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Eyes Wide Shut",
  "Year": "1999",
  "Rated": "R",
  "Released": "16 Jul 1999",
  "Runtime": "159 min",
  "Genre": "Drama, Mystery, Romance",
  "Director": "Stanley Kubrick",
  "Writer": "Stanley Kubrick (screenplay), Frederic Raphael (screenplay), Arthur Schnitzler (inspired by the novel by)",
  "Actors": "Tom Cruise, Nicole Kidman, Sydney Pollack, Marie Richardson",
  "Plot": "A New York City doctor, who is married to an art curator, pushes himself on a harrowing and dangerous night-long odyssey of sexual and moral discovery after his wife admits that she once almost cheated on him.",
  "Language": "English",
  "Country": "UK, USA",
  "Awards": "Nominated for 1 Golden Globe. Another 5 wins & 23 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMjA5NTUwNjI1N15BMl5BanBnXkFtZTYwOTE1ODc5._V1_SX300.jpg",
  "Metascore": "68",
  "imdbRating": "7.3",
  "imdbVotes": "194,844",
  "imdbID": "tt0120663",
  "Type": "movie",
  "Response": "True"
}
//
//       How to incorporate food into sex
{
  "Title": "Last Tango in Paris",
  "Year": "1972",
  "Rated": "NC-17",
  "Released": "07 Feb 1973",
  "Runtime": "129 min",
  "Genre": "Drama, Romance",
  "Director": "Bernardo Bertolucci",
  "Writer": "Bernardo Bertolucci (story), Bernardo Bertolucci (screenplay), Franco Arcalli (screenplay), Agnès Varda (adaptation), Jean-Louis Trintignant (dialogue collaborator)",
  "Actors": "Marlon Brando, Maria Schneider, Maria Michi, Giovanna Galletti",
  "Plot": "A young Parisian woman meets a middle-aged American businessman who demands their clandestine relationship be based only on sex.",
  "Language": "English, French",
  "Country": "France, Italy",
  "Awards": "Nominated for 2 Oscars. Another 7 wins & 6 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMjE5ODQyMTI0OV5BMl5BanBnXkFtZTcwODgyNTEzNA@@._V1_SX300.jpg",
  "Metascore": "77",
  "imdbRating": "7.2",
  "imdbVotes": "31,115",
  "imdbID": "tt0070849",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Varsity Blues",
  "Year": "1999",
  "Rated": "R",
  "Released": "15 Jan 1999",
  "Runtime": "106 min",
  "Genre": "Comedy, Drama, Romance",
  "Director": "Brian Robbins",
  "Writer": "W. Peter Iliff",
  "Actors": "James Van Der Beek, Jon Voight, Paul Walker, Ron Lester",
  "Plot": "In small-town Texas, high school football is a religion. The head coach is deified, as long as the team is winning and 17-year-old schoolboys carry the hopes of an entire community onto the...",
  "Language": "English",
  "Country": "USA",
  "Awards": "2 wins & 4 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTc2OTMxOTQzNV5BMl5BanBnXkFtZTgwMzAxNzQxMTE@._V1_SX300.jpg",
  "Metascore": "50",
  "imdbRating": "6.4",
  "imdbVotes": "32,173",
  "imdbID": "tt0139699",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Nine 1/2 Weeks",
  "Year": "1986",
  "Rated": "R",
  "Released": "21 Feb 1986",
  "Runtime": "117 min",
  "Genre": "Drama, Romance",
  "Director": "Adrian Lyne",
  "Writer": "Sarah Kernochan, Zalman King, Patricia Louisianna Knop, Elizabeth McNeill (novel)",
  "Actors": "Kim Basinger, Mickey Rourke, Margaret Whitton, David Margulies",
  "Plot": "A woman gets involved in an impersonal affair with a man. She barely knows about his life, only about the sex games they play, so the relationship begins to get complicated.",
  "Language": "English, Spanish",
  "Country": "USA",
  "Awards": "3 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMjE1NDY1NjA4MV5BMl5BanBnXkFtZTYwMzU0Mzk4._V1_SX300.jpg",
  "Metascore": "50",
  "imdbRating": "5.8",
  "imdbVotes": "25,282",
  "imdbID": "tt0091635",
  "Type": "movie",
  "Response": "True"
}
//
//       Heartbroken
<<<<<<< HEAD
//       It’s OK, all you need is your dog. But he’ll die soon.
//       My Dog Skip,
//       Marley and Me
//       Old Yeller
//       What doesn’t kill you will leave you scarred for the rest of your life
//       My Girl,
//       Man in the Moon,
//       Snakes on a Plane
//
//
=======
{
  "Title": "My Dog Skip",
  "Year": "2000",
  "Rated": "PG",
  "Released": "03 Mar 2000",
  "Runtime": "95 min",
  "Genre": "Drama, Family, Sport",
  "Director": "Jay Russell",
  "Writer": "Willie Morris (book), Gail Gilchriest (screenplay)",
  "Actors": "Frankie Muniz, Diane Lane, Luke Wilson, Kevin Bacon",
  "Plot": "A shy boy grows up in 1940s Mississippi with the help of his beloved dog, Skip.",
  "Language": "English, German",
  "Country": "USA",
  "Awards": "6 wins & 4 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTc1NDgxMjg5MV5BMl5BanBnXkFtZTYwNTUxODc5._V1_SX300.jpg",
  "Metascore": "61",
  "imdbRating": "7.0",
  "imdbVotes": "15,367",
  "imdbID": "tt0156812",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Marley & Me",
  "Year": "2008",
  "Rated": "PG",
  "Released": "25 Dec 2008",
  "Runtime": "115 min",
  "Genre": "Comedy, Drama, Family",
  "Director": "David Frankel",
  "Writer": "Scott Frank (screenplay), Don Roos (screenplay), John Grogan (book)",
  "Actors": "Owen Wilson, Jennifer Aniston, Eric Dane, Kathleen Turner",
  "Plot": "A family learns important life lessons from their adorable, but naughty and neurotic dog.",
  "Language": "English",
  "Country": "USA",
  "Awards": "2 wins & 4 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BNTU1OTg1MTc3OV5BMl5BanBnXkFtZTcwMjI0OTc5MQ@@._V1_SX300.jpg",
  "Metascore": "53",
  "imdbRating": "7.1",
  "imdbVotes": "100,828",
  "imdbID": "tt0822832",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Old Yeller",
  "Year": "1957",
  "Rated": "Approved",
  "Released": "25 Dec 1957",
  "Runtime": "83 min",
  "Genre": "Family, Drama, Adventure",
  "Director": "Robert Stevenson",
  "Writer": "Fred Gipson (screenplay), William Tunberg (screenplay), Fred Gipson (book)",
  "Actors": "Dorothy McGuire, Fess Parker, Jeff York, Chuck Connors",
  "Plot": "A boy brings a yellow dog home. The dog loves the family as much as they love him, but can the love last ?",
  "Language": "English",
  "Country": "USA",
  "Awards": "1 win.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTI2MTcwNjAwNF5BMl5BanBnXkFtZTcwMTYzODAzMQ@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "7.3",
  "imdbVotes": "7,327",
  "imdbID": "tt0050798",
  "Type": "movie",
  "Response": "True"
}


//  What doesn’t kill you will leave you scarred for the rest of your life
{
  "Title": "My Girl",
  "Year": "1991",
  "Rated": "PG-13",
  "Released": "27 Nov 1991",
  "Runtime": "102 min",
  "Genre": "Drama, Family, Romance",
  "Director": "Howard Zieff",
  "Writer": "Laurice Elehwany",
  "Actors": "Dan Aykroyd, Jamie Lee Curtis, Macaulay Culkin, Anna Chlumsky",
  "Plot": "A young girl, on the threshold of her teen years, finds her life turning upside down, when she is accompanied by an unlikely friend.",
  "Language": "English",
  "Country": "USA",
  "Awards": "2 wins & 4 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMTkwNjA5MzQ2OV5BMl5BanBnXkFtZTcwMjAxMDYyMQ@@._V1_SX300.jpg",
  "Metascore": "N/A",
  "imdbRating": "6.8",
  "imdbVotes": "48,816",
  "imdbID": "tt0102492",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Man on the Moon",
  "Year": "1999",
  "Rated": "R",
  "Released": "22 Dec 1999",
  "Runtime": "118 min",
  "Genre": "Biography, Comedy, Drama",
  "Director": "Milos Forman",
  "Writer": "Scott Alexander, Larry Karaszewski",
  "Actors": "Jim Carrey, Gerry Becker, Greyson Erik Pendry, Brittany Colonna",
  "Plot": "The life and career of a legendary comedian, Andy Kaufman.",
  "Language": "English",
  "Country": "UK, Germany, Japan, USA",
  "Awards": "Won 1 Golden Globe. Another 4 wins & 21 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMjA0ODEwMzEzNl5BMl5BanBnXkFtZTYwMTcyODQ5._V1_SX300.jpg",
  "Metascore": "58",
  "imdbRating": "7.5",
  "imdbVotes": "91,381",
  "imdbID": "tt0125664",
  "Type": "movie",
  "Response": "True"
},
{
  "Title": "Snakes on a Plane",
  "Year": "2006",
  "Rated": "R",
  "Released": "18 Aug 2006",
  "Runtime": "105 min",
  "Genre": "Action, Thriller",
  "Director": "David R. Ellis",
  "Writer": "John Heffernan (screenplay), Sebastian Gutierrez (screenplay), David Dalessandro (story), John Heffernan (story)",
  "Actors": "Samuel L. Jackson, Julianna Margulies, Nathan Phillips, Rachel Blanchard",
  "Plot": "An FBI agent takes on a plane full of deadly and poisonous snakes, deliberately released to kill a witness being flown from Honolulu to Los Angeles to testify against a mob boss.",
  "Language": "English",
  "Country": "Germany, USA, Canada",
  "Awards": "1 win & 6 nominations.",
  "Poster": "http://ia.media-imdb.com/images/M/MV5BMjE0NzI3MjkxM15BMl5BanBnXkFtZTcwNjEzODIzMQ@@._V1_SX300.jpg",
  "Metascore": "58",
  "imdbRating": "5.6",
  "imdbVotes": "107,926",
  "imdbID": "tt0417148",
  "Type": "movie",
  "Response": "True"
}
>>>>>>> b308502a6464934a130271e90fcbe029cc0aa36d
